apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/change-cause: "{{ .Values.deployment.changeCause }}"
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.maxSurge }}
      maxUnavailable: {{ .Values.deployment.strategy.maxUnavailable }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: html-volume
        emptyDir: {}
      initContainers:
      - name: init-html
        image: busybox
        command:
          - sh
          - -c
          - |
            MY_POD_IP=$(hostname -i)
            cat > /usr/share/nginx/html/index.html <<EOF
            <html>
            <head>
                <title>Nginx Webserver</title>
                <style>
                    body {
                        background-color: #6495ED;
                        color: white;
                        font-size: 36px;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                        height: 100vh;
                        margin: 0;
                        font-family: Arial, sans-serif;
                    }
                </style>
            </head>
            <body>
                <div>This page is delivered from replica at IP: $MY_POD_IP v2</div>
            </body>
            </html>
            EOF
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
